- name: Install packages for apt
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present

- name: Add Docker's GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes

- name: Install Docker package
  package:
    name: docker-ce
    state: present

- name: Configure daemon
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker.daemon | default(docker_daemon_default) | to_nice_json }}"
  notify: Restart Docker

- name: Log in registry
  when: docker.registry is defined
  community.general.docker_login:
    registry_url: "{{ docker.registry.url }}"
    username: "{{ docker.registry.username }}"
    password: "{{ docker.registry.password }}"
