- name: Install packages for apt
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present

- name: Add Docker repository
  deb822_repository:
    name: docker
    uris: https://download.docker.com/linux/{{ ansible_distribution | lower }}
    suites: "{{ ansible_distribution_release }}"
    components: stable
    signed_by: https://download.docker.com/linux/debian/gpg
  notify: Update apt cache

- name: Fetch Docker repository
  meta: flush_handlers

- name: Install Docker package
  package:
    name: docker-ce
    state: present

- name: Configure daemon
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker.daemon | default(docker_daemon_default) | to_nice_json }}"
  notify: Restart Docker

- name: Log in registry
  when: docker.registry is defined
  community.general.docker_login:
    registry_url: "{{ docker.registry.url }}"
    username: "{{ docker.registry.username }}"
    password: "{{ docker.registry.password }}"
